---
title: "Introduction to the Critical Textbook of Psychology"
author: "Gjalt-Jorn Peters"
date: "2017-06-29"
params:
  id: "ctp-intro"
  keywords: ["methodology", "scientific method"]
  parents: ["none"]
  type: "standalone"
  source: ""
  status: "draft"
  version: "1.0"
  language: "en"
---

This is the Critical Textbook of Psychology.

# History of this textbook

(this content is, for now, just taken directly from the `README.md` file at https://github.com/psytext/ctp)

This idea developed in the PsychMAP Facebook group that developed after Michael Inzlicht posted http://www.vox.com/science-and-health/2017/1/5/14171140/psychology-textbooks-misinforming-students.

The idea is to create a new textbook, unlike other textbooks in a number of respects. First, initially at least there won't actually be a physical book :-) In this respect the initiative is comparable to the Noba Project (http://nobaproject.com/). Second, the idea is to pay attention to the quality of the evidence: in that sense, it's a methodologically/statistically informed textbook. For example, the power to detect small and medium effects could be included in the discussion of all studies, or funnel plots could be included, etc. Third, it may be possible to extend the Noba concept a bit by letting each chapter (sections/fragments - without a book, we needn't call them chapters I guess) specify its 'didactic dependencies': the other chapters/sections/fragments that a reader should have read before reading a given chapter (think of, e.g., the little movies in the Khan Academy, or maybe the packages in R). The CTP wouldn't need to be linear. Like with Noba, instructors could choose which chapters/elements/fragments to include, and the didactic dependencies would enable them to organise them into a coherent textbook.

Or, well, this are some first ideas. Anything's up for discussions!
